main.tf: add explicit project field to google_project_iam_member
This is necessary for 'terraform validate' to pass since bumping google
provider version.

Otherwise, the following error appears:

> Error: Missing required argument
>
>   on main.tf line 143, in resource "google_project_iam_member"
> "gha-coordinator-sa-role":
>  143: resource "google_project_iam_member" "gha-coordinator-sa-role" {
>
> The argument "project" is required, but no definition was found.